- debug:
    msg: node

- name: "Install nvm"
  git:
    repo: https://github.com/creationix/nvm.git
    version: v0.33.11
    dest: "{{ ansible_env.HOME }}/.nvm"

- name: "check if node 8 is installed"
  shell: |-
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
    nvm ls 8
  register: node_install
  changed_when: false
  failed_when: false

- name: "Install node"
  shell: |-
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
    nvm install 8
  when: node_install.rc != 0

- name: touch .npmrc
  file:
    path: "{{ ansible_env.HOME }}/.npmrc"
    state: touch
    mode: 0644
  # https://github.com/ansible/ansible-modules-core/issues/170
  register: touch_log
  changed_when: touch_log.diff.before.state != "file" or touch_log.diff.before.mode is defined

# marker 가 여러줄이면 무조건 changed 되버리는 버그가 있다
- blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR PROXY"
    path: ~/.npmrc
    content: "{{ node_npmrc_proxy }}"
