- name: apt proxy configure
  become: true
  copy:
    content: "{{ apt_company_proxy }}"
    dest: /etc/apt/apt.conf.d/200company-proxy.conf
  when: ansible_os_family == "Debian"

- name: copy company.crt file into home directory
  copy:
    content: "{{ EXTRA_VAR_CA_CERT }}"
    dest: "~{{ ansible_user_id }}/company.crt"
  when: EXTRA_VAR_CA_CERT is defined

- name: delete company.crt file
  file:
    path: "~{{ ansible_user_id }}/company.crt"
    state: absent
  when: EXTRA_VAR_CA_CERT is not defined

- name: copy proxyrc file if proxy is used
  copy:
    dest: "~{{ ansible_user_id }}/proxyrc"
    mode: 0644
    content: "{{ zsh_proxyrc }}"
  when: EXTRA_VAR_PROXY_SERVER_URL is defined

- name: delete proxyrc file if proxy is not used
  file:
    path: "~{{ ansible_user_id }}/proxyrc"
    state: absent
  when: EXTRA_VAR_PROXY_SERVER_URL is not defined

- name: copy proxyrc-unset file if proxy is used
  copy:
    dest: "~{{ ansible_user_id }}/proxyrc-unset"
    mode: 0644
    content: "{{ zsh_proxyrc_unset }}"
  when: EXTRA_VAR_PROXY_SERVER_URL is defined

- name: delete proxyrc-unset file if proxy is not used
  file:
    path: "~{{ ansible_user_id }}/proxyrc-unset"
    state: absent
  when: EXTRA_VAR_PROXY_SERVER_URL is not defined

- blockinfile:
    marker: "  # {mark} ANSIBLE MANAGED BLOCK FOR GIT_PROXY"
    path: "~{{ ansible_user_id }}/.gitconfig"
    content: "{{ git_proxy }}"
    create: true

- blockinfile:
    marker: "  # {mark} ANSIBLE MANAGED BLOCK FOR GIT_NO_PROXY"
    path: "~{{ ansible_user_id }}/.gitconfig"
    content: "{{ git_no_proxy }}"
    create: true
