- import_role:
    name: Stouts.python
  become: true
  vars:
    python_ppa: ppa:deadsnakes/ppa
    python_versions: ["3.6"]

- name: ensure pip packages
  become: true
  pip:
    executable: pip3.6
    extra_args:
    state: latest
    name:
      - awscli
      - docker-compose
